import type { CommandDef } from "./types.js";

export const executionCommands: CommandDef[] = [
  {
    name: "document-requests fulfill",
    description: "Document Requests Fulfill",
    route: { method: "PATCH", path: "/v1/document-requests/{pos}/fulfill" },
    entity: true,
    args: [{ name: "request-id", required: true, description: "Request Id" }],
    examples: ["corp document-requests fulfill <request-id>"],
  },
  {
    name: "document-requests not-applicable",
    description: "Document Requests Not Applicable",
    route: { method: "PATCH", path: "/v1/document-requests/{pos}/not-applicable" },
    entity: true,
    args: [{ name: "request-id", required: true, description: "Request Id" }],
    examples: ["corp document-requests not-applicable <request-id>"],
  },
  {
    name: "entities approval-artifacts",
    description: "Entities Approval Artifacts",
    route: { method: "GET", path: "/v1/entities/{eid}/approval-artifacts" },
    entity: true,
    display: { title: "Entities Approval Artifacts", cols: ["#approval_artifact_id>ID", "approved_at>Approved At", "approver_identity>Approver Identity", "channel>Channel", "@created_at>Created At", "#entity_id>ID", "expires_at>Expires At", "explicit>Explicit"] },
    examples: ["corp entities approval-artifacts", "corp entities approval-artifacts --json"],
  },
  {
    name: "entities intents",
    description: "Entities Intents",
    route: { method: "GET", path: "/v1/entities/{eid}/intents" },
    entity: true,
    display: { title: "Entities Intents", cols: ["authority_tier>Authority Tier", "authorized_at>Authorized At", "#bound_approval_artifact_id>ID", "bound_document_request_ids>Bound Document Request Ids", "cancelled_at>Cancelled At", "@created_at>Created At", "description>Description", "#entity_id>ID"] },
    examples: ["corp entities intents", "corp entities intents --json"],
  },
  {
    name: "entities obligations",
    description: "Entities Obligations",
    route: { method: "GET", path: "/v1/entities/{eid}/obligations" },
    entity: true,
    display: { title: "Entities Obligations", cols: ["#assignee_id>ID", "assignee_type>Assignee Type", "@created_at>Created At", "description>Description", "@due_date>Due Date", "#entity_id>ID", "expired_at>Expired At", "fulfilled_at>Fulfilled At"] },
    examples: ["corp entities obligations", "corp entities obligations --json"],
  },
  {
    name: "entities obligations-human",
    description: "Entities Obligations Human",
    route: { method: "GET", path: "/v1/entities/{eid}/obligations/human" },
    entity: true,
    display: { title: "Entities Obligations Human", cols: ["#assignee_id>ID", "assignee_type>Assignee Type", "@created_at>Created At", "description>Description", "@due_date>Due Date", "#entity_id>ID", "expired_at>Expired At", "fulfilled_at>Fulfilled At"] },
    examples: ["corp entities obligations-human", "corp entities obligations-human --json"],
  },
  {
    name: "entities obligations-summary",
    description: "Entities Obligations Summary",
    route: { method: "GET", path: "/v1/entities/{eid}/obligations/summary" },
    entity: true,
    display: { title: "Entities Obligations Summary", cols: ["expired>Expired", "fulfilled>Fulfilled", "pending>Pending", "total>Total", "waived>Waived"] },
    examples: ["corp entities obligations-summary", "corp entities obligations-summary --json"],
  },
  {
    name: "entities packets",
    description: "Entities Packets",
    route: { method: "GET", path: "/v1/entities/{eid}/packets" },
    entity: true,
    display: { title: "Entities Packets", cols: ["@created_at>Created At", "#entity_id>ID", "finalized_at>Finalized At", "#intent_id>ID", "items>Items", "manifest_hash>Manifest Hash", "#packet_id>ID", "required_signers>Required Signers"] },
    examples: ["corp entities packets", "corp entities packets --json"],
  },
  {
    name: "execution approval-artifacts",
    description: "Execution Approval Artifacts",
    route: { method: "POST", path: "/v1/execution/approval-artifacts" },
    options: [
      { flags: "--approved-at <approved-at>", description: "Approved At" },
      { flags: "--approver-identity <approver-identity>", description: "Approver Identity", required: true },
      { flags: "--channel <channel>", description: "Channel", required: true },
      { flags: "--expires-at <expires-at>", description: "Expires At" },
      { flags: "--explicit", description: "Explicit" },
      { flags: "--intent-type <intent-type>", description: "Intent Type", required: true },
      { flags: "--max-amount-cents <max-amount-cents>", description: "Max Amount Cents" },
      { flags: "--scope <scope>", description: "Scope", required: true },
    ],
    examples: ["corp execution approval-artifacts --approver-identity 'approver-identity' --channel 'channel' --intent-type 'intent-type' --scope 'scope'", "corp execution approval-artifacts --json"],
  },
  {
    name: "execution intents",
    description: "Execution Intents",
    route: { method: "POST", path: "/v1/execution/intents" },
    options: [
      { flags: "--authority-tier <authority-tier>", description: "Authority Tier", choices: ["tier_1", "tier_2", "tier_3"] },
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--intent-type <intent-type>", description: "Intent Type", required: true },
      { flags: "--metadata <metadata>", description: "Metadata" },
    ],
    examples: ["corp execution intents --description 'description' --intent-type 'intent-type'", "corp execution intents --json"],
  },
  {
    name: "execution obligations",
    description: "Execution Obligations",
    route: { method: "POST", path: "/v1/execution/obligations" },
    options: [
      { flags: "--assignee-id <assignee-id>", description: "Assignee Id" },
      { flags: "--assignee-type <assignee-type>", description: "Who is responsible for fulfilling an obligation.", required: true, choices: ["internal", "third_party", "human"] },
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--due-date <due-date>", description: "Due Date" },
      { flags: "--intent-id <intent-id>", description: "Intent Id" },
      { flags: "--obligation-type <obligation-type>", description: "Obligation Type", required: true },
    ],
    examples: ["corp execution obligations --assignee-type internal --description 'description' --obligation-type 'obligation-type'", "corp execution obligations --json"],
  },
  {
    name: "execution packets",
    description: "Execution Packets",
    route: { method: "GET", path: "/v1/execution/packets/{pos}" },
    entity: true,
    args: [{ name: "packet-id", required: true, description: "Packet Id" }],
    display: { title: "Execution Packets", cols: ["@created_at>Created At", "#entity_id>ID", "finalized_at>Finalized At", "#intent_id>ID", "items>Items", "manifest_hash>Manifest Hash", "#packet_id>ID", "required_signers>Required Signers"] },
    examples: ["corp execution packets", "corp execution packets --json"],
  },
  {
    name: "intents authorize",
    description: "Intents Authorize",
    route: { method: "POST", path: "/v1/intents/{pos}/authorize" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    examples: ["corp intents authorize <intent-id>"],
  },
  {
    name: "intents bind-approval-artifact",
    description: "Intents Bind Approval Artifact",
    route: { method: "POST", path: "/v1/intents/{pos}/bind-approval-artifact" },
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    options: [
      { flags: "--approval-artifact-id <approval-artifact-id>", description: "Approval Artifact Id", required: true },
    ],
    examples: ["corp intents bind-approval-artifact <intent-id> --approval-artifact-id 'approval-artifact-id'"],
  },
  {
    name: "intents bind-document-request",
    description: "Intents Bind Document Request",
    route: { method: "POST", path: "/v1/intents/{pos}/bind-document-request" },
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    options: [
      { flags: "--request-id <request-id>", description: "Request Id", required: true },
    ],
    examples: ["corp intents bind-document-request <intent-id> --request-id 'request-id'"],
  },
  {
    name: "intents cancel",
    description: "Intents Cancel",
    route: { method: "POST", path: "/v1/intents/{pos}/cancel" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    examples: ["corp intents cancel <intent-id>"],
  },
  {
    name: "intents evaluate",
    description: "Intents Evaluate",
    route: { method: "POST", path: "/v1/intents/{pos}/evaluate" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    examples: ["corp intents evaluate <intent-id>"],
  },
  {
    name: "intents execute",
    description: "Intents Execute",
    route: { method: "POST", path: "/v1/intents/{pos}/execute" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    examples: ["corp intents execute <intent-id>"],
  },
  {
    name: "intents receipts",
    description: "Intents Receipts",
    route: { method: "GET", path: "/v1/intents/{pos}/receipts" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    display: { title: "Intents Receipts", cols: ["@created_at>Created At", "executed_at>Executed At", "idempotency_key>Idempotency Key", "#intent_id>ID", "#receipt_id>ID", "request_hash>Request Hash", "response_hash>Response Hash", "status>Status"] },
    examples: ["corp intents receipts", "corp intents receipts --json"],
  },
  {
    name: "obligations assign",
    description: "Obligations Assign",
    route: { method: "POST", path: "/v1/obligations/{pos}/assign" },
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
    options: [
      { flags: "--assignee-id <assignee-id>", description: "Assignee Id", required: true },
    ],
    examples: ["corp obligations assign <obligation-id> --assignee-id 'assignee-id'"],
  },
  {
    name: "obligations document-requests",
    description: "Obligations Document Requests",
    route: { method: "GET", path: "/v1/obligations/{pos}/document-requests" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
    display: { title: "Obligations Document Requests", cols: ["@created_at>Created At", "description>Description", "document_type>Document Type", "#entity_id>ID", "fulfilled_at>Fulfilled At", "not_applicable_at>Not Applicable At", "#obligation_id>ID", "#request_id>ID"] },
    examples: ["corp obligations document-requests", "corp obligations document-requests --json"],
  },
  {
    name: "obligations document-requests",
    description: "Obligations Document Requests",
    route: { method: "POST", path: "/v1/obligations/{pos}/document-requests" },
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
    options: [
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--document-type <document-type>", description: "Document Type", required: true },
    ],
    examples: ["corp obligations document-requests <obligation-id> --description 'description' --document-type 'document-type'"],
  },
  {
    name: "obligations expire",
    description: "Obligations Expire",
    route: { method: "POST", path: "/v1/obligations/{pos}/expire" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
    examples: ["corp obligations expire <obligation-id>"],
  },
  {
    name: "obligations fulfill",
    description: "Obligations Fulfill",
    route: { method: "POST", path: "/v1/obligations/{pos}/fulfill" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
    examples: ["corp obligations fulfill <obligation-id>"],
  },
  {
    name: "obligations waive",
    description: "Obligations Waive",
    route: { method: "POST", path: "/v1/obligations/{pos}/waive" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
    examples: ["corp obligations waive <obligation-id>"],
  },
  {
    name: "receipts",
    description: "Receipts",
    route: { method: "GET", path: "/v1/receipts/{pos}" },
    entity: true,
    args: [{ name: "receipt-id", required: true, description: "Receipt Id" }],
    display: { title: "Receipts", cols: ["@created_at>Created At", "executed_at>Executed At", "idempotency_key>Idempotency Key", "#intent_id>ID", "#receipt_id>ID", "request_hash>Request Hash", "response_hash>Response Hash", "status>Status"] },
    examples: ["corp receipts", "corp receipts --json"],
  },

  // ── Human obligations ───────────────────────────────────────────────
  {
    name: "human-obligations",
    description: "List human obligations (signing, document upload, etc.)",
    route: { method: "GET", path: "/v1/human-obligations" },
    display: {
      title: "Human Obligations",
      cols: ["obligation_type>Type", "status>Status", "@due_at>Due", "#obligation_id>ID"],
    },
    examples: ["corp human-obligations"],
  },
  {
    name: "human-obligations fulfill",
    description: "Fulfill a human obligation",
    route: { method: "POST", path: "/v1/human-obligations/{pos}/fulfill" },
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    successTemplate: "Obligation fulfilled",
    examples: ["corp human-obligations fulfill <obligation-id>"],
  },
  {
    name: "human-obligations signer-token",
    description: "Get a signer token for a human obligation",
    route: { method: "POST", path: "/v1/human-obligations/{pos}/signer-token" },
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    successTemplate: "Signer token issued",
    examples: ["corp human-obligations signer-token <obligation-id>"],
  },
];