import type { CommandDef } from "./types.js";

export const executionCommands: CommandDef[] = [
  {
    name: "document-requests fulfill",
    description: "Fulfill a document request with uploaded content",
    route: { method: "PATCH", path: "/v1/document-requests/{pos}/fulfill" },
    entity: true,
    args: [{ name: "request-id", required: true, description: "Document request ID" }],
    examples: ["corp document-requests fulfill <request-id>"],
    successTemplate: "Fulfill updated",
  },
  {
    name: "document-requests not-applicable",
    description: "Mark a document request as not applicable",
    route: { method: "PATCH", path: "/v1/document-requests/{pos}/not-applicable" },
    entity: true,
    args: [{ name: "request-id", required: true, description: "Document request ID" }],
    examples: ["corp document-requests not-applicable <request-id>"],
    successTemplate: "Not Applicable updated",
  },
  {
    name: "entities approval-artifacts",
    description: "List approval artifacts for an entity",
    route: { method: "GET", path: "/v1/entities/{eid}/approval-artifacts" },
    entity: true,
    display: { title: "Entities Approval Artifacts", cols: ["approved_at>Approved At", "approver_identity>Approver Identity", "channel>Channel", "expires_at>Expires At", "@created_at>Created At", "#approval_artifact_id>ID"] },
    examples: ["corp entities approval-artifacts", "corp entities approval-artifacts --json"],
  },
  {
    name: "entities intents",
    description: "List execution intents for an entity",
    route: { method: "GET", path: "/v1/entities/{eid}/intents" },
    entity: true,
    display: { title: "Entities Intents", cols: ["authority_tier>Authority Tier", "authorized_at>Authorized At", "bound_document_request_ids>Bound Document Request Ids", "cancelled_at>Cancelled At", "@created_at>Created At", "#bound_approval_artifact_id>ID"] },
    examples: ["corp entities intents", "corp entities intents --json"],
  },
  {
    name: "entities obligations",
    description: "List obligations for an entity",
    route: { method: "GET", path: "/v1/entities/{eid}/obligations" },
    entity: true,
    display: { title: "Entities Obligations", cols: ["assignee_type>Assignee Type", "description>Description", "expired_at>Expired At", "fulfilled_at>Fulfilled At", "@created_at>Created At", "#assignee_id>ID"] },
    examples: ["corp entities obligations", "corp entities obligations --json"],
  },
  {
    name: "entities obligations-human",
    description: "List human-actionable obligations for an entity",
    route: { method: "GET", path: "/v1/entities/{eid}/obligations/human" },
    entity: true,
    display: { title: "Entities Obligations Human", cols: ["assignee_type>Assignee Type", "description>Description", "expired_at>Expired At", "fulfilled_at>Fulfilled At", "@created_at>Created At", "#assignee_id>ID"] },
    examples: ["corp entities obligations-human", "corp entities obligations-human --json"],
  },
  {
    name: "entities obligations-summary",
    description: "View obligation summary (pending/fulfilled/expired)",
    route: { method: "GET", path: "/v1/entities/{eid}/obligations/summary" },
    entity: true,
    display: { title: "Entities Obligations Summary", cols: ["expired>Expired", "fulfilled>Fulfilled", "pending>Pending", "total>Total", "waived>Waived"] },
    examples: ["corp entities obligations-summary", "corp entities obligations-summary --json"],
  },
  {
    name: "entities packets",
    description: "List document packets for an entity",
    route: { method: "GET", path: "/v1/entities/{eid}/packets" },
    entity: true,
    display: { title: "Entities Packets", cols: ["finalized_at>Finalized At", "items>Items", "manifest_hash>Manifest Hash", "required_signers>Required Signers", "@created_at>Created At", "#entity_id>ID"] },
    examples: ["corp entities packets", "corp entities packets --json"],
  },
  {
    name: "execution approval-artifacts",
    description: "Create an approval artifact (e.g. board vote record)",
    route: { method: "POST", path: "/v1/execution/approval-artifacts" },
    options: [
      { flags: "--approved-at <approved-at>", description: "Timestamp of approval (ISO 8601)" },
      { flags: "--approver-identity <approver-identity>", description: "Identity of the approver", required: true },
      { flags: "--channel <channel>", description: "Approval channel (board_vote, written_consent, etc.)", required: true },
      { flags: "--expires-at <expires-at>", description: "Expiration timestamp (ISO 8601)" },
      { flags: "--explicit", description: "Whether approval is explicit (vs implied)" },
      { flags: "--intent-type <intent-type>", description: "Type of intent", required: true },
      { flags: "--max-amount-cents <max-amount-cents>", description: "Maximum authorized amount in cents" },
      { flags: "--scope <scope>", description: "Authorization scope", required: true },
    ],
    examples: ["corp execution approval-artifacts --approver-identity 'approver-identity' --channel 'channel' --intent-type 'intent-type' --scope 'scope'", "corp execution approval-artifacts --json"],
    successTemplate: "Approval Artifacts created",
  },
  {
    name: "execution intents",
    description: "Create an execution intent (action requiring authorization)",
    route: { method: "POST", path: "/v1/execution/intents" },
    entity: true,
    options: [
      { flags: "--authority-tier <authority-tier>", description: "Authority tier required (tier_1, tier_2, tier_3)", choices: ["tier_1", "tier_2", "tier_3"] },
      { flags: "--description <description>", description: "Description text", required: true },
      { flags: "--intent-type <intent-type>", description: "Type of intent", required: true },
      { flags: "--metadata <metadata>", description: "Additional metadata (JSON)" },
    ],
    examples: ["corp execution intents --description 'description' --intent-type 'intent-type'", "corp execution intents --json"],
    successTemplate: "Intents created",
  },
  {
    name: "execution obligations",
    description: "Create an obligation (task assigned to a party)",
    route: { method: "POST", path: "/v1/execution/obligations" },
    options: [
      { flags: "--assignee-id <assignee-id>", description: "ID of the party to assign to" },
      { flags: "--assignee-type <assignee-type>", description: "Who is responsible for fulfilling an obligation.", required: true, choices: ["internal", "third_party", "human"] },
      { flags: "--description <description>", description: "Description text", required: true },
      { flags: "--due-date <due-date>", description: "Due date (ISO 8601, e.g. 2026-06-30)" },
      { flags: "--intent-id <intent-id>", description: "Execution intent ID" },
      { flags: "--obligation-type <obligation-type>", description: "Type of obligation", required: true },
    ],
    examples: ["corp execution obligations --assignee-type internal --description 'description' --obligation-type 'obligation-type'", "corp execution obligations --json"],
    successTemplate: "Obligations created",
  },
  {
    name: "execution packets",
    description: "View a document packet",
    route: { method: "GET", path: "/v1/execution/packets/{pos}" },
    entity: true,
    args: [{ name: "packet-id", required: true, description: "Document packet ID" }],
    display: { title: "Execution Packets", cols: ["finalized_at>Finalized At", "items>Items", "manifest_hash>Manifest Hash", "required_signers>Required Signers", "@created_at>Created At", "#entity_id>ID"] },
    examples: ["corp execution packets", "corp execution packets --json"],
  },
  {
    name: "intents authorize",
    description: "Authorize an execution intent",
    route: { method: "POST", path: "/v1/intents/{pos}/authorize" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Execution intent ID" }],
    examples: ["corp intents authorize <intent-id>"],
    successTemplate: "Authorize created",
  },
  {
    name: "intents bind-approval-artifact",
    description: "Bind an approval artifact to an intent",
    route: { method: "POST", path: "/v1/intents/{pos}/bind-approval-artifact" },
    args: [{ name: "intent-id", required: true, description: "Execution intent ID" }],
    options: [
      { flags: "--approval-artifact-id <approval-artifact-id>", description: "Approval artifact ID to bind", required: true },
    ],
    examples: ["corp intents bind-approval-artifact <intent-id> --approval-artifact-id 'approval-artifact-id'"],
    successTemplate: "Bind Approval Artifact created",
  },
  {
    name: "intents bind-document-request",
    description: "Bind a document request to an intent",
    route: { method: "POST", path: "/v1/intents/{pos}/bind-document-request" },
    args: [{ name: "intent-id", required: true, description: "Execution intent ID" }],
    options: [
      { flags: "--request-id <request-id>", description: "Document request ID", required: true },
    ],
    examples: ["corp intents bind-document-request <intent-id> --request-id 'request-id'"],
    successTemplate: "Bind Document Request created",
  },
  {
    name: "intents cancel",
    description: "Cancel an execution intent",
    route: { method: "POST", path: "/v1/intents/{pos}/cancel" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Execution intent ID" }],
    examples: ["corp intents cancel <intent-id>"],
    successTemplate: "Cancel created",
  },
  {
    name: "intents evaluate",
    description: "Evaluate whether an intent meets its requirements",
    route: { method: "POST", path: "/v1/intents/{pos}/evaluate" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Execution intent ID" }],
    examples: ["corp intents evaluate <intent-id>"],
    successTemplate: "Evaluate created",
  },
  {
    name: "intents execute",
    description: "Execute an authorized intent",
    route: { method: "POST", path: "/v1/intents/{pos}/execute" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Execution intent ID" }],
    examples: ["corp intents execute <intent-id>"],
    successTemplate: "Execute created",
  },
  {
    name: "intents receipts",
    description: "View execution receipts for an intent",
    route: { method: "GET", path: "/v1/intents/{pos}/receipts" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Execution intent ID" }],
    display: { title: "Intents Receipts", cols: ["executed_at>Executed At", "idempotency_key>Idempotency Key", "request_hash>Request Hash", "response_hash>Response Hash", "@created_at>Created At", "#intent_id>ID"] },
    examples: ["corp intents receipts", "corp intents receipts --json"],
  },
  {
    name: "obligations assign",
    description: "Assign an obligation to a party",
    route: { method: "POST", path: "/v1/obligations/{pos}/assign" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    options: [
      { flags: "--assignee-id <assignee-id>", description: "ID of the party to assign to", required: true },
    ],
    examples: ["corp obligations assign <obligation-id> --assignee-id 'assignee-id'"],
    successTemplate: "Assign created",
  },
  {
    name: "obligations document-requests",
    description: "List or create document requests for an obligation",
    route: { method: "GET", path: "/v1/obligations/{pos}/document-requests" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    display: { title: "Obligations Document Requests", cols: ["description>Description", "document_type>Document Type", "fulfilled_at>Fulfilled At", "not_applicable_at>Not Applicable At", "@created_at>Created At", "#entity_id>ID"] },
    examples: ["corp obligations document-requests", "corp obligations document-requests --json"],
  },
  {
    name: "obligations create-document-request",
    description: "List or create document requests for an obligation",
    route: { method: "POST", path: "/v1/obligations/{pos}/document-requests" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    options: [
      { flags: "--description <description>", description: "Description text", required: true },
      { flags: "--document-type <document-type>", description: "Type of document required", required: true },
    ],
    examples: ["corp obligations document-requests <obligation-id> --description 'description' --document-type 'document-type'"],
    successTemplate: "Document Requests created",
  },
  {
    name: "obligations expire",
    description: "Mark an obligation as expired",
    route: { method: "POST", path: "/v1/obligations/{pos}/expire" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    examples: ["corp obligations expire <obligation-id>"],
    successTemplate: "Expire created",
  },
  {
    name: "obligations fulfill",
    description: "Mark an obligation as fulfilled",
    route: { method: "POST", path: "/v1/obligations/{pos}/fulfill" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    examples: ["corp obligations fulfill <obligation-id>"],
    successTemplate: "Fulfill created",
  },
  {
    name: "obligations waive",
    description: "Waive an obligation",
    route: { method: "POST", path: "/v1/obligations/{pos}/waive" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    examples: ["corp obligations waive <obligation-id>"],
    successTemplate: "Waive created",
  },
  {
    name: "receipts",
    description: "View an execution receipt",
    route: { method: "GET", path: "/v1/receipts/{pos}" },
    entity: true,
    args: [{ name: "receipt-id", required: true, description: "Execution receipt ID" }],
    display: { title: "Receipts", cols: ["executed_at>Executed At", "idempotency_key>Idempotency Key", "request_hash>Request Hash", "response_hash>Response Hash", "@created_at>Created At", "#intent_id>ID"] },
    examples: ["corp receipts", "corp receipts --json"],
  },

  // ── Human obligations ───────────────────────────────────────────────
  {
    name: "human-obligations",
    description: "List obligations requiring human action (signing, upload)",
    route: { method: "GET", path: "/v1/human-obligations" },
    display: {
      title: "Human Obligations",
      cols: ["obligation_type>Type", "status>Status", "@due_at>Due", "#obligation_id>ID"],
    },
    examples: ["corp human-obligations"],
  },
  {
    name: "human-obligations fulfill",
    description: "Fulfill a human obligation",
    route: { method: "POST", path: "/v1/human-obligations/{pos}/fulfill" },
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    successTemplate: "Obligation fulfilled",
    examples: ["corp human-obligations fulfill <obligation-id>"],
  },
  {
    name: "human-obligations signer-token",
    description: "Get a signing token for a human obligation",
    route: { method: "POST", path: "/v1/human-obligations/{pos}/signer-token" },
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    successTemplate: "Signer token issued",
    examples: ["corp human-obligations signer-token <obligation-id>"],
  },
];