import type { CommandDef } from "./types.js";

export const executionCommands: CommandDef[] = [
  {
    name: "document-requests fulfill",
    description: "/v1/document-requests/{request_id}/fulfill",
    route: { method: "PATCH", path: "/v1/document-requests/{pos}/fulfill" },
    entity: true,
    args: [{ name: "request-id", required: true, description: "Request Id" }],
  },
  {
    name: "document-requests not-applicable",
    description: "/v1/document-requests/{request_id}/not-applicable",
    route: { method: "PATCH", path: "/v1/document-requests/{pos}/not-applicable" },
    entity: true,
    args: [{ name: "request-id", required: true, description: "Request Id" }],
  },
  {
    name: "entities approval-artifacts",
    description: "/v1/entities/{entity_id}/approval-artifacts",
    route: { method: "GET", path: "/v1/entities/{eid}/approval-artifacts" },
    entity: true,
    display: { title: "Entities Approval Artifacts", cols: ["#approval_artifact_id>ID", "approved_at>Approved At", "approver_identity>Approver Identity", "channel>Channel", "@created_at>Created At", "#entity_id>ID", "expires_at>Expires At", "explicit>Explicit"] },
  },
  {
    name: "entities intents",
    description: "/v1/entities/{entity_id}/intents",
    route: { method: "GET", path: "/v1/entities/{eid}/intents" },
    entity: true,
    display: { title: "Entities Intents", cols: ["authority_tier>Authority Tier", "authorized_at>Authorized At", "#bound_approval_artifact_id>ID", "bound_document_request_ids>Bound Document Request Ids", "cancelled_at>Cancelled At", "@created_at>Created At", "description>Description", "#entity_id>ID"] },
  },
  {
    name: "entities obligations",
    description: "/v1/entities/{entity_id}/obligations",
    route: { method: "GET", path: "/v1/entities/{eid}/obligations" },
    entity: true,
    display: { title: "Entities Obligations", cols: ["#assignee_id>ID", "assignee_type>Assignee Type", "@created_at>Created At", "description>Description", "@due_date>Due Date", "#entity_id>ID", "expired_at>Expired At", "fulfilled_at>Fulfilled At"] },
  },
  {
    name: "entities obligations-human",
    description: "/v1/entities/{entity_id}/obligations/human",
    route: { method: "GET", path: "/v1/entities/{eid}/obligations/human" },
    entity: true,
    display: { title: "Entities Obligations Human", cols: ["#assignee_id>ID", "assignee_type>Assignee Type", "@created_at>Created At", "description>Description", "@due_date>Due Date", "#entity_id>ID", "expired_at>Expired At", "fulfilled_at>Fulfilled At"] },
  },
  {
    name: "entities obligations-summary",
    description: "/v1/entities/{entity_id}/obligations/summary",
    route: { method: "GET", path: "/v1/entities/{eid}/obligations/summary" },
    entity: true,
    display: { title: "Entities Obligations Summary", cols: ["expired>Expired", "fulfilled>Fulfilled", "pending>Pending", "total>Total", "waived>Waived"] },
  },
  {
    name: "entities packets",
    description: "/v1/entities/{entity_id}/packets",
    route: { method: "GET", path: "/v1/entities/{eid}/packets" },
    entity: true,
    display: { title: "Entities Packets", cols: ["@created_at>Created At", "#entity_id>ID", "finalized_at>Finalized At", "#intent_id>ID", "items>Items", "manifest_hash>Manifest Hash", "#packet_id>ID", "required_signers>Required Signers"] },
  },
  {
    name: "execution approval-artifacts",
    description: "/v1/execution/approval-artifacts",
    route: { method: "POST", path: "/v1/execution/approval-artifacts" },
    options: [
      { flags: "--approved-at <approved-at>", description: "Approved At" },
      { flags: "--approver-identity <approver-identity>", description: "Approver Identity", required: true },
      { flags: "--channel <channel>", description: "Channel", required: true },
      { flags: "--expires-at <expires-at>", description: "Expires At" },
      { flags: "--explicit", description: "Explicit" },
      { flags: "--intent-type <intent-type>", description: "Intent Type", required: true },
      { flags: "--max-amount-cents <max-amount-cents>", description: "Max Amount Cents" },
      { flags: "--scope <scope>", description: "Scope", required: true },
    ],
  },
  {
    name: "execution intents",
    description: "/v1/execution/intents",
    route: { method: "POST", path: "/v1/execution/intents" },
    options: [
      { flags: "--authority-tier <authority-tier>", description: "Authority Tier", choices: ["tier_1", "tier_2", "tier_3"] },
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--intent-type <intent-type>", description: "Intent Type", required: true },
      { flags: "--metadata <metadata>", description: "Metadata" },
    ],
  },
  {
    name: "execution obligations",
    description: "/v1/execution/obligations",
    route: { method: "POST", path: "/v1/execution/obligations" },
    options: [
      { flags: "--assignee-id <assignee-id>", description: "Assignee Id" },
      { flags: "--assignee-type <assignee-type>", description: "Who is responsible for fulfilling an obligation.", required: true, choices: ["internal", "third_party", "human"] },
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--due-date <due-date>", description: "Due Date" },
      { flags: "--intent-id <intent-id>", description: "Intent Id" },
      { flags: "--obligation-type <obligation-type>", description: "Obligation Type", required: true },
    ],
  },
  {
    name: "execution packets",
    description: "/v1/execution/packets/{packet_id}",
    route: { method: "GET", path: "/v1/execution/packets/{pos}" },
    entity: true,
    args: [{ name: "packet-id", required: true, description: "Packet Id" }],
    display: { title: "Execution Packets", cols: ["@created_at>Created At", "#entity_id>ID", "finalized_at>Finalized At", "#intent_id>ID", "items>Items", "manifest_hash>Manifest Hash", "#packet_id>ID", "required_signers>Required Signers"] },
  },
  {
    name: "intents authorize",
    description: "/v1/intents/{intent_id}/authorize",
    route: { method: "POST", path: "/v1/intents/{pos}/authorize" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
  },
  {
    name: "intents bind-approval-artifact",
    description: "/v1/intents/{intent_id}/bind-approval-artifact",
    route: { method: "POST", path: "/v1/intents/{pos}/bind-approval-artifact" },
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    options: [
      { flags: "--approval-artifact-id <approval-artifact-id>", description: "Approval Artifact Id", required: true },
    ],
  },
  {
    name: "intents bind-document-request",
    description: "/v1/intents/{intent_id}/bind-document-request",
    route: { method: "POST", path: "/v1/intents/{pos}/bind-document-request" },
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    options: [
      { flags: "--request-id <request-id>", description: "Request Id", required: true },
    ],
  },
  {
    name: "intents cancel",
    description: "/v1/intents/{intent_id}/cancel",
    route: { method: "POST", path: "/v1/intents/{pos}/cancel" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
  },
  {
    name: "intents evaluate",
    description: "/v1/intents/{intent_id}/evaluate",
    route: { method: "POST", path: "/v1/intents/{pos}/evaluate" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
  },
  {
    name: "intents execute",
    description: "/v1/intents/{intent_id}/execute",
    route: { method: "POST", path: "/v1/intents/{pos}/execute" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
  },
  {
    name: "intents receipts",
    description: "/v1/intents/{intent_id}/receipts",
    route: { method: "GET", path: "/v1/intents/{pos}/receipts" },
    entity: true,
    args: [{ name: "intent-id", required: true, description: "Intent Id" }],
    display: { title: "Intents Receipts", cols: ["@created_at>Created At", "executed_at>Executed At", "idempotency_key>Idempotency Key", "#intent_id>ID", "#receipt_id>ID", "request_hash>Request Hash", "response_hash>Response Hash", "status>Status"] },
  },
  {
    name: "obligations assign",
    description: "/v1/obligations/{obligation_id}/assign",
    route: { method: "POST", path: "/v1/obligations/{pos}/assign" },
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
    options: [
      { flags: "--assignee-id <assignee-id>", description: "Assignee Id", required: true },
    ],
  },
  {
    name: "obligations document-requests",
    description: "/v1/obligations/{obligation_id}/document-requests",
    route: { method: "GET", path: "/v1/obligations/{pos}/document-requests" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
    display: { title: "Obligations Document Requests", cols: ["@created_at>Created At", "description>Description", "document_type>Document Type", "#entity_id>ID", "fulfilled_at>Fulfilled At", "not_applicable_at>Not Applicable At", "#obligation_id>ID", "#request_id>ID"] },
  },
  {
    name: "obligations document-requests",
    description: "/v1/obligations/{obligation_id}/document-requests",
    route: { method: "POST", path: "/v1/obligations/{pos}/document-requests" },
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
    options: [
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--document-type <document-type>", description: "Document Type", required: true },
    ],
  },
  {
    name: "obligations expire",
    description: "/v1/obligations/{obligation_id}/expire",
    route: { method: "POST", path: "/v1/obligations/{pos}/expire" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
  },
  {
    name: "obligations fulfill",
    description: "/v1/obligations/{obligation_id}/fulfill",
    route: { method: "POST", path: "/v1/obligations/{pos}/fulfill" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
  },
  {
    name: "obligations waive",
    description: "/v1/obligations/{obligation_id}/waive",
    route: { method: "POST", path: "/v1/obligations/{pos}/waive" },
    entity: true,
    args: [{ name: "obligation-id", required: true, description: "Obligation Id" }],
  },
  {
    name: "receipts",
    description: "/v1/receipts/{receipt_id}",
    route: { method: "GET", path: "/v1/receipts/{pos}" },
    entity: true,
    args: [{ name: "receipt-id", required: true, description: "Receipt Id" }],
    display: { title: "Receipts", cols: ["@created_at>Created At", "executed_at>Executed At", "idempotency_key>Idempotency Key", "#intent_id>ID", "#receipt_id>ID", "request_hash>Request Hash", "response_hash>Response Hash", "status>Status"] },
  },

  // ── Human obligations ───────────────────────────────────────────────
  {
    name: "human-obligations",
    description: "List human obligations (signing, document upload, etc.)",
    route: { method: "GET", path: "/v1/human-obligations" },
    display: {
      title: "Human Obligations",
      cols: ["obligation_type>Type", "status>Status", "@due_at>Due", "#obligation_id>ID"],
    },
  },
  {
    name: "human-obligations fulfill",
    description: "Fulfill a human obligation",
    route: { method: "POST", path: "/v1/human-obligations/{pos}/fulfill" },
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    successTemplate: "Obligation fulfilled",
  },
  {
    name: "human-obligations signer-token",
    description: "Get a signer token for a human obligation",
    route: { method: "POST", path: "/v1/human-obligations/{pos}/signer-token" },
    args: [{ name: "obligation-id", required: true, description: "Obligation ID" }],
    successTemplate: "Signer token issued",
  },
];