import type { CommandDef } from "./types.js";

export const treasuryCommands: CommandDef[] = [
  {
    name: "bank-accounts close",
    description: "Close a bank account",
    route: { method: "POST", path: "/v1/bank-accounts/{pos}/close" },
    entity: true,
    args: [{ name: "bank-account-id", required: true, description: "Bank account ID", posKind: "bank_account" }],
    examples: ["corp bank-accounts close ba_01hx9k3n2p4q7r8s9t0uvwxyz"],
    successTemplate: "Bank account closed",
  },
  {
    name: "distributions",
    description: "Record a distribution (dividend, member draw, or liquidation)",
    route: { method: "POST", path: "/v1/distributions" },
    options: [
      { flags: "--description <description>", description: "Description text", required: true },
      { flags: "--distribution-type <distribution-type>", description: "Type of distribution", choices: ["dividend", "return", "liquidation"] },
      { flags: "--total-amount-cents <total-amount-cents>", description: "Total amount in cents (e.g. 500000 for $5,000)", required: true, type: "int" },
    ],
    examples: [
      'corp distributions --description "Q1 dividend" --distribution-type dividend --total-amount-cents 500000',
      'corp distributions --description "Founder draw" --distribution-type return --total-amount-cents 1000000',
    ],
    successTemplate: "Distribution recorded",
  },
  {
    name: "entities accounts",
    description: "List ledger accounts for an entity",
    route: { method: "GET", path: "/v1/entities/{eid}/accounts" },
    entity: true,
    display: { title: "Entities Accounts", cols: ["account_code>Account Code", "account_name>Account Name", "account_type>Account Type", "currency>Currency", "@created_at>Created At", "#account_id>ID"] },
    examples: ["corp entities accounts", "corp entities accounts --json"],
  },
  {
    name: "entities journal-entries",
    description: "List journal entries for an entity",
    route: { method: "GET", path: "/v1/entities/{eid}/journal-entries" },
    entity: true,
    display: { title: "Entities Journal Entries", cols: ["description>Description", "effective_date>Effective Date", "status>Status", "total_credits_cents>Total Credits Cents", "@created_at>Created At", "#entity_id>ID"] },
    examples: ["corp entities journal-entries", "corp entities journal-entries --json"],
  },
  {
    name: "entities spending-limits",
    description: "List spending limits for an entity",
    route: { method: "GET", path: "/v1/entities/{eid}/spending-limits" },
    entity: true,
    display: { title: "Entities Spending Limits", cols: ["amount_cents>Amount Cents", "category>Category", "@created_at>Created At", "#entity_id>ID", "period>Period", "#spending_limit_id>ID"] },
    examples: ["corp entities spending-limits", "corp entities spending-limits --json"],
  },
  {
    name: "entities stripe-account",
    description: "View Stripe account details for an entity",
    route: { method: "GET", path: "/v1/entities/{eid}/stripe-account" },
    entity: true,
    display: { title: "Entities Stripe Account", cols: ["@created_at>Created At", "#entity_id>ID", "status>Status", "#stripe_account_id>ID"] },
    examples: ["corp entities stripe-account", "corp entities stripe-account --json"],
  },
  {
    name: "invoices from-agent-request",
    description: "Create an invoice from an agent request",
    route: { method: "POST", path: "/v1/invoices/from-agent-request" },
    entity: true,
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Invoice amount in cents (e.g. 500000 for $5,000)", required: true, type: "int" },
      { flags: "--customer-name <customer-name>", description: "Customer name for the invoice", required: true },
      { flags: "--description <description>", description: "Description of the services or goods invoiced", required: true },
      { flags: "--due-date <due-date>", description: "Payment due date (ISO 8601, e.g. 2026-06-30)", required: true },
    ],
    examples: [
      'corp invoices from-agent-request --amount-cents 500000 --customer-name "Acme Corp" --description "Consulting services Q1" --due-date 2026-06-30',
    ],
    successTemplate: "Invoice created from agent request",
  },
  {
    name: "invoices",
    description: "View an invoice by ID",
    route: { method: "GET", path: "/v1/invoices/{pos}" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice ID", posKind: "invoice" }],
    display: { title: "Invoices", cols: ["amount_cents>Amount Cents", "customer_name>Customer Name", "description>Description", "status>Status", "@created_at>Created At", "#entity_id>ID"] },
    examples: [
      "corp invoices inv_01hx9k3n2p4q7r8s9t0uvwxyz",
      "corp invoices inv_01hx9k3n2p4q7r8s9t0uvwxyz --json",
    ],
  },
  {
    name: "invoices mark-paid",
    description: "Mark an invoice as paid",
    route: { method: "POST", path: "/v1/invoices/{pos}/mark-paid" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice ID", posKind: "invoice" }],
    examples: ["corp invoices mark-paid inv_01hx9k3n2p4q7r8s9t0uvwxyz"],
    successTemplate: "Invoice marked as paid",
  },
  {
    name: "invoices pay-instructions",
    description: "Get payment instructions for an invoice",
    route: { method: "GET", path: "/v1/invoices/{pos}/pay-instructions" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice ID", posKind: "invoice" }],
    display: { title: "Invoices Pay Instructions", cols: ["amount_cents>Amount Cents", "currency>Currency", "instructions>Instructions", "#invoice_id>ID", "payment_method>Payment Method"] },
    examples: [
      "corp invoices pay-instructions inv_01hx9k3n2p4q7r8s9t0uvwxyz",
      "corp invoices pay-instructions inv_01hx9k3n2p4q7r8s9t0uvwxyz --json",
    ],
  },
  {
    name: "invoices send",
    description: "Send an invoice to the recipient",
    route: { method: "POST", path: "/v1/invoices/{pos}/send" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice ID", posKind: "invoice" }],
    examples: ["corp invoices send inv_01hx9k3n2p4q7r8s9t0uvwxyz"],
    successTemplate: "Invoice sent",
  },
  {
    name: "invoices status",
    description: "Check payment status of an invoice",
    route: { method: "GET", path: "/v1/invoices/{pos}/status" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice ID", posKind: "invoice" }],
    display: { title: "Invoices Status", cols: ["amount_cents>Amount Cents", "customer_name>Customer Name", "description>Description", "status>Status", "@created_at>Created At", "#entity_id>ID"] },
    examples: [
      "corp invoices status inv_01hx9k3n2p4q7r8s9t0uvwxyz",
      "corp invoices status inv_01hx9k3n2p4q7r8s9t0uvwxyz --json",
    ],
  },
  {
    name: "journal-entries post",
    description: "Post a journal entry (make it permanent)",
    route: { method: "POST", path: "/v1/journal-entries/{pos}/post" },
    entity: true,
    args: [{ name: "entry-id", required: true, description: "Journal entry ID" }],
    examples: ["corp journal-entries post jrn_01hx9k3n2p4q7r8s9t0uvwxyz"],
    successTemplate: "Journal entry posted",
  },
  {
    name: "journal-entries void",
    description: "Void a journal entry",
    route: { method: "POST", path: "/v1/journal-entries/{pos}/void" },
    entity: true,
    args: [{ name: "entry-id", required: true, description: "Journal entry ID" }],
    examples: ["corp journal-entries void jrn_01hx9k3n2p4q7r8s9t0uvwxyz"],
    successTemplate: "Journal entry voided",
  },
  {
    name: "ledger reconcile",
    description: "Run a ledger reconciliation for an entity",
    route: { method: "POST", path: "/v1/ledger/reconcile" },
    entity: true,
    options: [
      { flags: "--as-of-date <as-of-date>", description: "Reconcile as of this date (ISO 8601, e.g. 2026-03-31)" },
      { flags: "--end-date <end-date>", description: "End of reconciliation period (ISO 8601)" },
      { flags: "--start-date <start-date>", description: "Start of reconciliation period (ISO 8601)" },
    ],
    examples: [
      "corp ledger reconcile --as-of-date 2026-03-31",
      "corp ledger reconcile --start-date 2026-01-01 --end-date 2026-03-31",
    ],
    successTemplate: "Ledger reconciliation complete",
  },
  {
    name: "payments",
    description: "Record a new payment",
    route: { method: "POST", path: "/v1/payments" },
    entity: true,
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Payment amount in cents (e.g. 500000 for $5,000)", required: true, type: "int" },
      { flags: "--description <description>", description: "Description of the payment", required: true },
      { flags: "--payment-method <payment-method>", description: "How the payment is made or received", choices: ["bank_transfer", "card", "check", "wire", "ach"] },
      { flags: "--recipient <recipient>", description: "Recipient name or ID", required: true },
    ],
    examples: [
      'corp payments --amount-cents 250000 --description "Software subscription" --payment-method ach --recipient "Acme Vendors LLC"',
      'corp payments --amount-cents 1000000 --description "Consulting invoice #42" --payment-method wire --recipient "Jane Doe"',
    ],
    successTemplate: "Payment recorded",
  },
  {
    name: "payments execute",
    description: "Execute a pending payment immediately",
    route: { method: "POST", path: "/v1/payments/execute" },
    entity: true,
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Payment amount in cents (e.g. 500000 for $5,000)", required: true, type: "int" },
      { flags: "--description <description>", description: "Description of the payment", required: true },
      { flags: "--payment-method <payment-method>", description: "How the payment is made or received", choices: ["bank_transfer", "card", "check", "wire", "ach"] },
      { flags: "--recipient <recipient>", description: "Recipient name or ID", required: true },
    ],
    examples: [
      'corp payments execute --amount-cents 250000 --description "Vendor invoice" --payment-method wire --recipient "Acme Vendors LLC"',
    ],
    successTemplate: "Payment executed",
  },
  {
    name: "payroll runs",
    description: "Create a payroll run for a pay period",
    route: { method: "POST", path: "/v1/payroll/runs" },
    entity: true,
    options: [
      { flags: "--pay-period-end <pay-period-end>", description: "Last day of the pay period (ISO 8601, e.g. 2026-03-31)", required: true },
      { flags: "--pay-period-start <pay-period-start>", description: "First day of the pay period (ISO 8601, e.g. 2026-03-01)", required: true },
    ],
    examples: [
      "corp payroll runs --pay-period-start 2026-03-01 --pay-period-end 2026-03-31",
    ],
    successTemplate: "Payroll run created",
  },
  {
    name: "spending-limits",
    description: "Set a spending limit for a category and period",
    route: { method: "POST", path: "/v1/spending-limits" },
    entity: true,
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Limit amount in cents (e.g. 500000 for $5,000)", required: true, type: "int" },
      { flags: "--category <category>", description: "Spending category (e.g. software, travel, marketing)", required: true },
      { flags: "--period <period>", description: "Limit period (e.g. monthly, quarterly, annual)", required: true },
    ],
    examples: [
      "corp spending-limits --amount-cents 500000 --category software --period monthly",
      "corp spending-limits --amount-cents 2000000 --category travel --period quarterly",
    ],
    successTemplate: "Spending limit set",
  },
  {
    name: "treasury accounts",
    description: "Create a new ledger account for an entity",
    route: { method: "POST", path: "/v1/treasury/accounts" },
    entity: true,
    options: [
      { flags: "--account-code <account-code>", description: "Standard GL account code to create", required: true, choices: ["Cash", "AccountsReceivable", "AccountsPayable", "AccruedExpenses", "FounderCapital", "Revenue", "OperatingExpenses", "Cogs"] },
    ],
    examples: [
      "corp treasury accounts --account-code Cash",
      "corp treasury accounts --account-code Revenue",
    ],
    successTemplate: "Ledger account created",
  },
  {
    name: "treasury bank-accounts",
    description: "Register a new bank account for an entity",
    route: { method: "POST", path: "/v1/treasury/bank-accounts" },
    entity: true,
    options: [
      { flags: "--account-type <account-type>", description: "Type of bank account", choices: ["checking", "savings"] },
      { flags: "--bank-name <bank-name>", description: "Name of the bank (e.g. Mercury, Chase)", required: true },
    ],
    examples: [
      "corp treasury bank-accounts --bank-name Mercury --account-type checking",
      "corp treasury bank-accounts --bank-name Chase --account-type savings",
    ],
    successTemplate: "Bank account registered",
  },
  {
    name: "treasury chart-of-accounts",
    description: "View the chart of accounts for an entity",
    route: { method: "GET", path: "/v1/treasury/chart-of-accounts/{eid}" },
    entity: true,
    display: { title: "Treasury Chart Of Accounts", cols: ["accounts>Accounts", "#entity_id>ID"] },
    examples: ["corp treasury chart-of-accounts", "corp treasury chart-of-accounts --json"],
  },
  {
    name: "treasury invoices",
    description: "Create a new invoice",
    route: { method: "POST", path: "/v1/treasury/invoices" },
    entity: true,
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Invoice amount in cents (e.g. 500000 for $5,000)", required: true, type: "int" },
      { flags: "--customer-name <customer-name>", description: "Customer name for the invoice", required: true },
      { flags: "--description <description>", description: "Description of services or goods invoiced", required: true },
      { flags: "--due-date <due-date>", description: "Payment due date (ISO 8601, e.g. 2026-06-30)", required: true },
    ],
    examples: [
      'corp treasury invoices --amount-cents 500000 --customer-name "Acme Corp" --description "Consulting services Q1" --due-date 2026-06-30',
    ],
    successTemplate: "Invoice created",
  },
  {
    name: "treasury journal-entries",
    description: "Create a journal entry",
    route: { method: "POST", path: "/v1/treasury/journal-entries" },
    entity: true,
    options: [
      { flags: "--description <description>", description: "Description of the journal entry", required: true },
      { flags: "--effective-date <effective-date>", description: "Date the entry takes effect (ISO 8601, e.g. 2026-03-31)", required: true },
      { flags: "--lines <lines>", description: "JSON array of debit/credit line items", required: true, type: "array" },
    ],
    examples: [
      'corp treasury journal-entries --description "Prepaid software expense" --effective-date 2026-03-31 --lines \'[{"account_code":"OperatingExpenses","amount_cents":50000,"type":"debit"},{"account_code":"Cash","amount_cents":50000,"type":"credit"}]\'',
    ],
    successTemplate: "Journal entry created",
  },
  {
    name: "treasury payment-intents",
    description: "Create a payment intent",
    route: { method: "POST", path: "/v1/treasury/payment-intents" },
    entity: true,
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Payment amount in cents (e.g. 500000 for $5,000)", required: true, type: "int" },
      { flags: "--currency <currency>", description: "ISO 4217 currency code (e.g. USD)" },
      { flags: "--description <description>", description: "Description of the payment" },
    ],
    examples: [
      'corp treasury payment-intents --amount-cents 500000 --currency USD --description "Vendor payment"',
    ],
    successTemplate: "Payment intent created",
  },
  {
    name: "treasury payouts",
    description: "Create a payout to a destination",
    route: { method: "POST", path: "/v1/treasury/payouts" },
    entity: true,
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Payout amount in cents (e.g. 500000 for $5,000)", required: true, type: "int" },
      { flags: "--description <description>", description: "Description of the payout" },
      { flags: "--destination <destination>", description: "Destination account or recipient ID", required: true },
    ],
    examples: [
      'corp treasury payouts --amount-cents 500000 --destination ba_01hx9k3n2p4q7r8s9t0uvwxyz --description "Founder distribution"',
    ],
    successTemplate: "Payout created",
  },
  {
    name: "treasury seed-chart-of-accounts",
    description: "Initialize the chart of accounts for an entity from a template",
    route: { method: "POST", path: "/v1/treasury/seed-chart-of-accounts" },
    entity: true,
    options: [
      { flags: "--template <template>", description: "Chart of accounts template to seed from (e.g. standard, startup)" },
    ],
    examples: [
      "corp treasury seed-chart-of-accounts",
      "corp treasury seed-chart-of-accounts --template startup",
    ],
    successTemplate: "Chart of accounts initialized",
  },
  {
    name: "treasury stripe-accounts",
    description: "Register a Stripe account for an entity",
    route: { method: "POST", path: "/v1/treasury/stripe-accounts" },
    entity: true,
    examples: ["corp treasury stripe-accounts"],
    successTemplate: "Stripe account registered",
  },

];
