import type { CommandDef } from "./types.js";

export const treasuryCommands: CommandDef[] = [
  {
    name: "bank-accounts close",
    description: "Bank Accounts Close",
    route: { method: "POST", path: "/v1/bank-accounts/{pos}/close" },
    entity: true,
    args: [{ name: "bank-account-id", required: true, description: "Bank Account Id" }],
    examples: ["corp bank-accounts close <bank-account-id>"],
  },
  {
    name: "distributions",
    description: "Distributions",
    route: { method: "POST", path: "/v1/distributions" },
    options: [
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--distribution-type <distribution-type>", description: "Type of distribution.", choices: ["dividend", "return", "liquidation"] },
      { flags: "--total-amount-cents <total-amount-cents>", description: "Total Amount Cents", required: true, type: "int" },
    ],
    examples: ["corp distributions --description dividend --total-amount-cents 'total-amount-cents'", "corp distributions --json"],
  },
  {
    name: "entities accounts",
    description: "Entities Accounts",
    route: { method: "GET", path: "/v1/entities/{eid}/accounts" },
    entity: true,
    display: { title: "Entities Accounts", cols: ["account_code>Account Code", "#account_id>ID", "account_name>Account Name", "account_type>Account Type", "@created_at>Created At", "currency>Currency", "#entity_id>ID", "is_active>Is Active"] },
    examples: ["corp entities accounts", "corp entities accounts --json"],
  },
  {
    name: "entities journal-entries",
    description: "Entities Journal Entries",
    route: { method: "GET", path: "/v1/entities/{eid}/journal-entries" },
    entity: true,
    display: { title: "Entities Journal Entries", cols: ["@created_at>Created At", "description>Description", "effective_date>Effective Date", "#entity_id>ID", "#journal_entry_id>ID", "status>Status", "total_credits_cents>Total Credits Cents", "total_debits_cents>Total Debits Cents"] },
    examples: ["corp entities journal-entries", "corp entities journal-entries --json"],
  },
  {
    name: "entities spending-limits",
    description: "Entities Spending Limits",
    route: { method: "GET", path: "/v1/entities/{eid}/spending-limits" },
    entity: true,
    display: { title: "Entities Spending Limits", cols: ["amount_cents>Amount Cents", "category>Category", "@created_at>Created At", "#entity_id>ID", "period>Period", "#spending_limit_id>ID"] },
    examples: ["corp entities spending-limits", "corp entities spending-limits --json"],
  },
  {
    name: "entities stripe-account",
    description: "Entities Stripe Account",
    route: { method: "GET", path: "/v1/entities/{eid}/stripe-account" },
    entity: true,
    display: { title: "Entities Stripe Account", cols: ["@created_at>Created At", "#entity_id>ID", "status>Status", "#stripe_account_id>ID"] },
    examples: ["corp entities stripe-account", "corp entities stripe-account --json"],
  },
  {
    name: "invoices from-agent-request",
    description: "Invoices From Agent Request",
    route: { method: "POST", path: "/v1/invoices/from-agent-request" },
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Amount Cents", required: true, type: "int" },
      { flags: "--customer-name <customer-name>", description: "Customer Name", required: true },
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--due-date <due-date>", description: "Due Date", required: true },
    ],
    examples: ["corp invoices from-agent-request --amount-cents 'amount-cents' --customer-name 'customer-name' --description 'description' --due-date 'due-date'"],
  },
  {
    name: "invoices",
    description: "Invoices",
    route: { method: "GET", path: "/v1/invoices/{pos}" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice Id" }],
    display: { title: "Invoices", cols: ["amount_cents>Amount Cents", "@created_at>Created At", "customer_name>Customer Name", "description>Description", "@due_date>Due Date", "#entity_id>ID", "#invoice_id>ID", "status>Status"] },
    examples: ["corp invoices", "corp invoices --json"],
  },
  {
    name: "invoices mark-paid",
    description: "Invoices Mark Paid",
    route: { method: "POST", path: "/v1/invoices/{pos}/mark-paid" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice Id" }],
    examples: ["corp invoices mark-paid <invoice-id>"],
  },
  {
    name: "invoices pay-instructions",
    description: "Invoices Pay Instructions",
    route: { method: "GET", path: "/v1/invoices/{pos}/pay-instructions" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice Id" }],
    display: { title: "Invoices Pay Instructions", cols: ["amount_cents>Amount Cents", "currency>Currency", "instructions>Instructions", "#invoice_id>ID", "payment_method>Payment Method"] },
    examples: ["corp invoices pay-instructions", "corp invoices pay-instructions --json"],
  },
  {
    name: "invoices send",
    description: "Invoices Send",
    route: { method: "POST", path: "/v1/invoices/{pos}/send" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice Id" }],
    examples: ["corp invoices send <invoice-id>"],
  },
  {
    name: "invoices status",
    description: "Invoices Status",
    route: { method: "GET", path: "/v1/invoices/{pos}/status" },
    entity: true,
    args: [{ name: "invoice-id", required: true, description: "Invoice Id" }],
    display: { title: "Invoices Status", cols: ["amount_cents>Amount Cents", "@created_at>Created At", "customer_name>Customer Name", "description>Description", "@due_date>Due Date", "#entity_id>ID", "#invoice_id>ID", "status>Status"] },
    examples: ["corp invoices status", "corp invoices status --json"],
  },
  {
    name: "journal-entries post",
    description: "Journal Entries Post",
    route: { method: "POST", path: "/v1/journal-entries/{pos}/post" },
    entity: true,
    args: [{ name: "entry-id", required: true, description: "Entry Id" }],
    examples: ["corp journal-entries post <entry-id>"],
  },
  {
    name: "journal-entries void",
    description: "Journal Entries Void",
    route: { method: "POST", path: "/v1/journal-entries/{pos}/void" },
    entity: true,
    args: [{ name: "entry-id", required: true, description: "Entry Id" }],
    examples: ["corp journal-entries void <entry-id>"],
  },
  {
    name: "ledger reconcile",
    description: "Ledger Reconcile",
    route: { method: "POST", path: "/v1/ledger/reconcile" },
    options: [
      { flags: "--as-of-date <as-of-date>", description: "As Of Date" },
      { flags: "--end-date <end-date>", description: "End Date" },
      { flags: "--start-date <start-date>", description: "Start Date" },
    ],
    examples: ["corp ledger reconcile", "corp ledger reconcile --json"],
  },
  {
    name: "payments",
    description: "Payments",
    route: { method: "POST", path: "/v1/payments" },
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Amount Cents", required: true, type: "int" },
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--payment-method <payment-method>", description: "How a payment is made or received.", choices: ["bank_transfer", "card", "check", "wire", "ach"] },
      { flags: "--recipient <recipient>", description: "Recipient", required: true },
    ],
    examples: ["corp payments --amount-cents 'amount-cents' --description bank_transfer --recipient 'recipient'", "corp payments --json"],
  },
  {
    name: "payments execute",
    description: "Payments Execute",
    route: { method: "POST", path: "/v1/payments/execute" },
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Amount Cents", required: true, type: "int" },
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--payment-method <payment-method>", description: "How a payment is made or received.", choices: ["bank_transfer", "card", "check", "wire", "ach"] },
      { flags: "--recipient <recipient>", description: "Recipient", required: true },
    ],
    examples: ["corp payments execute --amount-cents 'amount-cents' --description bank_transfer --recipient 'recipient'", "corp payments execute --json"],
  },
  {
    name: "payroll runs",
    description: "Payroll Runs",
    route: { method: "POST", path: "/v1/payroll/runs" },
    options: [
      { flags: "--pay-period-end <pay-period-end>", description: "Pay Period End", required: true },
      { flags: "--pay-period-start <pay-period-start>", description: "Pay Period Start", required: true },
    ],
    examples: ["corp payroll runs --pay-period-end 'pay-period-end' --pay-period-start 'pay-period-start'"],
  },
  {
    name: "spending-limits",
    description: "Spending Limits",
    route: { method: "POST", path: "/v1/spending-limits" },
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Amount Cents", required: true, type: "int" },
      { flags: "--category <category>", description: "Category", required: true },
      { flags: "--period <period>", description: "Period", required: true },
    ],
    examples: ["corp spending-limits --amount-cents 'amount-cents' --category 'category' --period 'period'"],
  },
  {
    name: "treasury accounts",
    description: "Treasury Accounts",
    route: { method: "POST", path: "/v1/treasury/accounts" },
    options: [
      { flags: "--account-code <account-code>", description: "Standard GL account codes with integer discriminants matching the code number.", required: true, choices: ["Cash", "AccountsReceivable", "AccountsPayable", "AccruedExpenses", "FounderCapital", "Revenue", "OperatingExpenses", "Cogs"] },
    ],
    examples: ["corp treasury accounts --account-code Cash"],
  },
  {
    name: "treasury bank-accounts",
    description: "Treasury Bank Accounts",
    route: { method: "POST", path: "/v1/treasury/bank-accounts" },
    options: [
      { flags: "--account-type <account-type>", description: "Account Type", choices: ["checking", "savings"] },
      { flags: "--bank-name <bank-name>", description: "Bank Name", required: true },
    ],
    examples: ["corp treasury bank-accounts --bank-name 'bank-name'", "corp treasury bank-accounts --json"],
  },
  {
    name: "treasury chart-of-accounts",
    description: "Treasury Chart Of Accounts",
    route: { method: "GET", path: "/v1/treasury/chart-of-accounts/{eid}" },
    entity: true,
    display: { title: "Treasury Chart Of Accounts", cols: ["accounts>Accounts", "#entity_id>ID"] },
    examples: ["corp treasury chart-of-accounts", "corp treasury chart-of-accounts --json"],
  },
  {
    name: "treasury invoices",
    description: "Treasury Invoices",
    route: { method: "POST", path: "/v1/treasury/invoices" },
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Amount Cents", required: true, type: "int" },
      { flags: "--customer-name <customer-name>", description: "Customer Name", required: true },
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--due-date <due-date>", description: "Due Date", required: true },
    ],
    examples: ["corp treasury invoices --amount-cents 'amount-cents' --customer-name 'customer-name' --description 'description' --due-date 'due-date'"],
  },
  {
    name: "treasury journal-entries",
    description: "Treasury Journal Entries",
    route: { method: "POST", path: "/v1/treasury/journal-entries" },
    options: [
      { flags: "--description <description>", description: "Description", required: true },
      { flags: "--effective-date <effective-date>", description: "Effective Date", required: true },
      { flags: "--lines <lines>", description: "Lines", required: true, type: "array" },
    ],
    examples: ["corp treasury journal-entries --description 'description' --effective-date 'effective-date' --lines 'lines'"],
  },
  {
    name: "treasury payment-intents",
    description: "Treasury Payment Intents",
    route: { method: "POST", path: "/v1/treasury/payment-intents" },
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Amount Cents", required: true, type: "int" },
      { flags: "--currency <currency>", description: "Currency" },
      { flags: "--description <description>", description: "Description" },
    ],
    examples: ["corp treasury payment-intents --amount-cents 'amount-cents'", "corp treasury payment-intents --json"],
  },
  {
    name: "treasury payouts",
    description: "Treasury Payouts",
    route: { method: "POST", path: "/v1/treasury/payouts" },
    options: [
      { flags: "--amount-cents <amount-cents>", description: "Amount Cents", required: true, type: "int" },
      { flags: "--description <description>", description: "Description" },
      { flags: "--destination <destination>", description: "Destination", required: true },
    ],
    examples: ["corp treasury payouts --amount-cents 'amount-cents' --destination 'destination'", "corp treasury payouts --json"],
  },
  {
    name: "treasury seed-chart-of-accounts",
    description: "Treasury Seed Chart Of Accounts",
    route: { method: "POST", path: "/v1/treasury/seed-chart-of-accounts" },
    options: [
      { flags: "--template <template>", description: "Template" },
    ],
    examples: ["corp treasury seed-chart-of-accounts", "corp treasury seed-chart-of-accounts --json"],
  },
  {
    name: "treasury stripe-accounts",
    description: "Treasury Stripe Accounts",
    route: { method: "POST", path: "/v1/treasury/stripe-accounts" },
    examples: ["corp treasury stripe-accounts"],
  },

];