import type { ResourceKind } from "./references.js";

export const KINDS = new Set<ResourceKind>([
  "entity",
  "contact",
  "share_transfer",
  "invoice",
  "bank_account",
  "payment",
  "payroll_run",
  "distribution",
  "reconciliation",
  "tax_filing",
  "deadline",
  "classification",
  "body",
  "meeting",
  "seat",
  "agenda_item",
  "resolution",
  "document",
  "work_item",
  "agent",
  "valuation",
  "safe_note",
  "instrument",
  "share_class",
  "round",
]);

export const ENTITY_SCOPED_KINDS = new Set<ResourceKind>([
  "contact",
  "share_transfer",
  "invoice",
  "bank_account",
  "payment",
  "payroll_run",
  "distribution",
  "reconciliation",
  "tax_filing",
  "deadline",
  "classification",
  "body",
  "meeting",
  "seat",
  "agenda_item",
  "resolution",
  "document",
  "work_item",
  "valuation",
  "safe_note",
  "instrument",
  "share_class",
  "round",
]);
