import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { randomBytes } from "node:crypto";
import type { ChildProcess } from "node:child_process";

interface ServeOptions {
  port: string;
  dataDir: string;
}

const ENV_TEMPLATE = `# Corporation API server configuration
# Generated by: corp serve

# Required — secret for signing JWTs
JWT_SECRET={{JWT_SECRET}}

# Required — Fernet key for encrypting secrets at rest (base64url, 32 bytes)
SECRETS_MASTER_KEY={{SECRETS_MASTER_KEY}}

# Required — bearer token for internal worker-to-server auth
INTERNAL_WORKER_TOKEN={{INTERNAL_WORKER_TOKEN}}

# Server port (default: 8000)
# PORT=8000

# Data directory for git repos (default: ./data/repos)
# DATA_DIR=./data/repos

# Redis URL for agent job queue (optional)
# REDIS_URL=redis://localhost:6379/0

# LLM proxy upstream (default: https://openrouter.ai/api/v1)
# LLM_UPSTREAM_URL=https://openrouter.ai/api/v1

# PEM-encoded Ed25519 key for signing git commits (optional)
# COMMIT_SIGNING_KEY=

# Max agent queue depth (default: 1000)
# MAX_QUEUE_DEPTH=1000
`;

function generateFernetKey(): string {
  // Fernet key = url-safe base64 of 32 random bytes
  return randomBytes(32).toString("base64url") + "=";
}

function generateSecret(length = 32): string {
  return randomBytes(length).toString("hex");
}

function loadEnvFile(path: string): void {
  if (!existsSync(path)) return;

  const content = readFileSync(path, "utf-8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, "");

    // Don't override vars already set in the environment
    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}

function ensureEnvFile(envPath: string): void {
  if (existsSync(envPath)) return;

  console.log("No .env file found. Generating one with dev defaults...\n");

  const content = ENV_TEMPLATE
    .replace("{{JWT_SECRET}}", generateSecret())
    .replace("{{SECRETS_MASTER_KEY}}", generateFernetKey())
    .replace("{{INTERNAL_WORKER_TOKEN}}", generateSecret());

  writeFileSync(envPath, content, "utf-8");
  console.log(`  Created ${envPath}\n`);
}

export async function serveCommand(opts: ServeOptions): Promise<void> {
  let server: { getBinaryPath: () => string | null; isAvailable: () => boolean; startServer: (options: Record<string, unknown>) => ChildProcess };
  try {
    server = await import("@thecorporation/server");
  } catch {
    console.error(
      "Error: @thecorporation/server is not installed.\n\n" +
      "Install it with:\n" +
      "  npm install @thecorporation/server\n\n" +
      "Or run the Rust binary directly:\n" +
      "  cd services/api-rs && cargo run"
    );
    process.exit(1);
  }

  if (!server.isAvailable()) {
    console.error(
      "Error: No server binary available for this platform.\n\n" +
      "Pre-built binaries are available for:\n" +
      "  - linux-x64, linux-arm64\n" +
      "  - darwin-x64, darwin-arm64\n" +
      "  - win32-x64\n\n" +
      "You can build from source:\n" +
      "  cd services/api-rs && cargo build --release"
    );
    process.exit(1);
  }

  const port = parseInt(opts.port, 10);
  if (isNaN(port) || port > 65535) {
    console.error(`Error: Invalid port "${opts.port}"`);
    process.exit(1);
  }

  // Load .env file, generating one if it doesn't exist
  const envPath = resolve(process.cwd(), ".env");
  ensureEnvFile(envPath);
  loadEnvFile(envPath);

  // Auto-configure CLI to point at the local server
  const localUrl = `http://localhost:${port}`;
  const { loadConfig, saveConfig } = await import("../config.js");
  const cfg = loadConfig();
  const previousUrl = cfg.api_url;
  if (cfg.api_url !== localUrl) {
    cfg.api_url = localUrl;
    saveConfig(cfg);
    console.log(`CLI configured to use local server: ${localUrl}`);
    console.log(`  (previous: ${previousUrl})`);
    console.log(`  To revert: corp config set api_url ${previousUrl}\n`);
  }

  console.log(`Starting server on port ${port}...`);
  console.log(`Data directory: ${opts.dataDir}`);

  const child = server.startServer({
    port,
    dataDir: opts.dataDir,
  });

  const shutdown = () => {
    console.log("\nShutting down server...");
    // Restore previous API URL
    if (previousUrl !== localUrl) {
      const current = loadConfig();
      current.api_url = previousUrl;
      saveConfig(current);
      console.log(`CLI restored to: ${previousUrl}`);
    }
    child.kill("SIGTERM");
  };

  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  child.on("exit", (code) => {
    process.exit(code ?? 0);
  });
}
