import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { randomBytes } from "node:crypto";

const ENV_TEMPLATE = `# Corporation API server configuration
# Generated by: corp serve

# Required — secret for signing JWTs
JWT_SECRET={{JWT_SECRET}}

# Required — Fernet key for encrypting secrets at rest (base64url, 32 bytes)
SECRETS_MASTER_KEY={{SECRETS_MASTER_KEY}}

# Required — bearer token for internal worker-to-server auth
INTERNAL_WORKER_TOKEN={{INTERNAL_WORKER_TOKEN}}

# Server port (default: 8000)
# PORT=8000

# Data directory for git repos (default: ./data/repos)
# DATA_DIR=./data/repos

# Redis URL for agent job queue (optional)
# REDIS_URL=redis://localhost:6379/0

# LLM proxy upstream (default: https://openrouter.ai/api/v1)
# LLM_UPSTREAM_URL=https://openrouter.ai/api/v1

# PEM-encoded Ed25519 key for signing git commits (optional)
# COMMIT_SIGNING_KEY=

# Max agent queue depth (default: 1000)
# MAX_QUEUE_DEPTH=1000
`;

export function generateFernetKey(): string {
  // Fernet key = url-safe base64 of 32 random bytes
  return randomBytes(32).toString("base64url") + "=";
}

export function generateSecret(length = 32): string {
  return randomBytes(length).toString("hex");
}

export function loadEnvFile(path: string): void {
  if (!existsSync(path)) return;

  const content = readFileSync(path, "utf-8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, "");

    // Don't override vars already set in the environment
    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}

export function ensureEnvFile(envPath: string): void {
  if (existsSync(envPath)) return;

  console.log("No .env file found. Generating one with dev defaults...\n");

  const content = ENV_TEMPLATE
    .replace("{{JWT_SECRET}}", generateSecret())
    .replace("{{SECRETS_MASTER_KEY}}", generateFernetKey())
    .replace("{{INTERNAL_WORKER_TOKEN}}", generateSecret());

  writeFileSync(envPath, content, "utf-8");
  console.log(`  Created ${envPath}\n`);
}
